version: '3'
services:
  backend:
    image: ghcr.io/integrated-project-int221/backend:master
    restart: always
    container_name: api-container
    

  frontend:
    image: ghcr.io/integrated-project-int221/frontend:master
    container_name: frontend-container
    depends_on:
      - backend

  reverseproxy:
    container_name: reverseproxy-container
    image: nginx:1.17.10
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend      
    ports:
      - "80:80"



networks:
  default:
    external:
      name: database_myproduct-network

