version: '3'
services:
    database:
        build: ./database
        restart: always
        container_name: mysql
        volumes:
            - .database/scriptmysql/mysql-data:/var/lib/mysql
            - .database/scriptmysql/:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"
    backend:
        build: ./backend
        restart: always
        container_name: backend
        ports:
          - "3000:3000"
        depends_on: 
            - database
    frontend:
        build: ./frontend
        restart: always
        container_name: frontend
        depends_on: 
            - database
            - backend
    reverseproxy:
        image: nginx
        restart: always
        container_name: reverse_proxy
        volumes: 
            - ./reverseproxy/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - database
            - backend
            - frontend
        ports: 
            - "80:80"

networks:
    default:
      external:
        name: project
